name: Deploy to GitHub Pages

# ⚠️ NOTE: This workflow is OPTIONAL and currently has environment validation issues
# GitHub Pages works perfectly fine without it using the branch-based deployment method
# To use branch-based deployment instead:
# 1. Go to Settings → Pages in your repository
# 2. Select Source: Deploy from a branch
# 3. Choose branch: develop (or main)
# 4. Choose folder: / (root)
# 5. Click Save
#
# You can safely delete this file if you prefer the simpler branch-based method

on:
  push:
    branches:
      - develop  # Change to 'main' if using main branch
  workflow_dispatch:  # Allows manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
